CREATE TABLE IF NOT EXISTS controversial_topics(
  id INT  PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS options_of_topic(
      id BIGSERIAL PRIMARY KEY,
      option_id INT,
      controversial_topics_id INT,
      topic_option VARCHAR(255),
      FOREIGN KEY (controversial_topics_id) REFERENCES controversial_topics(id)
);

INSERT INTO controversial_topics (id, name, description) VALUES
  (0, 'Surveillance_Privacy', 'Balancing national security concerns with individual privacy rights.'),
  (1, 'Immigration_Policy', 'Debates over immigration laws and their impact on the economy and national identity.'),
  (2, 'Affirmative_Action', 'The use and fairness of affirmative action in education and employment.'),
  (3, 'Capitalism_vs_Socialism', 'Economic systems and which is more beneficial for society.'),
  (4, 'Universal_Healthcare', 'Should healthcare be free and provided by the government.'),
  (5, 'Same_Sex_Marriage', 'Legalization and recognition of same-sex marriages.'),
  (6, 'Gender_Identity', 'Recognition and rights of transgender and non-binary individuals.'),
  (7, 'Role_of_Religion', 'The role of religion in public life and government.'),
  (8, 'Censorship_Freedom_of_Speech', 'The limits of free speech and the role of censorship.'),
  (9, 'Social_Media_Impact', 'The effects of social media on communication and society.'),
  (10, 'Police_Brutality', 'Issues of police violence and systemic racism.'),
  (11, 'Foreign_Policy', 'The approach to international relations and military interventions.'),
  (12, 'Welfare_State', 'The extent of government support for citizens.'),
  (13, 'Artificial_Intelligence', 'The rise of AI and its impact on employment and ethics.'),
  (14, 'Gig_Economy', 'The changing nature of work and workers rights.'),
  (15, 'Net_Neutrality', 'The regulation of internet service providers and information flow.'),
  (16, 'Student_Loan_Debt', 'The growing crisis of student debt.'),
  (17, 'Obesity_Epidemic', 'Public health concerns and the role of the food industry.'),
  (18, 'Nuclear_Energy', 'The use of nuclear power and its safety.'),
  (19, 'Cultural_Appropriation', 'The borrowing of cultural elements and its implications.'),
  (20, 'Gig_Worker_Rights', 'The rights and protections for gig economy workers.'),
  (21, 'Role_of_NATO_UN', 'The effectiveness and role of international organizations.'),
  (22, 'Human_Genetic_Modification', 'Ethics of modifying human DNA for health or enhancement.'),
  (23, 'Space_Colonization', 'The ethics and feasibility of colonizing other planets.'),
  (24, 'Artificial_Wombs', 'The implications of ectogenesis on society and reproductive rights.'),
  (25, 'Use_of_Drones', 'The use of drones in warfare and surveillance.'),
  (26, 'Age_of_Consent_Laws', 'Debating the appropriate age of consent for sexual activities.'),
  (27, 'Corporate_Lobbying', 'The influence of corporate money in politics.'),
  (28, 'Sex_Work_Legalization', 'The debate over the legalization and regulation of sex work.'),
  (29, 'Pharmaceutical_Industry_Ethics', 'The ethics of drug pricing and access to medication.'),
  (30, 'Minimum_Wage', 'The impact of raising the minimum wage on the economy and workers.'),
  (31, 'Role_of_Monarchy', 'The relevance and power of monarchies in the modern world.'),
  (32, 'Free_Trade_vs_Protectionism', 'The benefits and drawbacks of free trade vs. protective tariffs.'),
  (33, 'Performance_Enhancing_Drugs', 'The use of steroids and other drugs in sports.'),
  (34, 'Media_Bias', 'Concerns over bias in the media and its impact on public opinion.'),
  (35, 'Cryptocurrency_Future', 'The stability and regulation of cryptocurrencies.'),
  (36, 'Population_Control', 'Ethical concerns over government involvement in population control.'),
  (37, 'Right_to_Bear_Arms', 'Gun ownership rights and public safety concerns.'),
  (38, 'Technology_Impact_on_Children', 'The influence of technology on child development and behavior.'),
  (39, 'Church_and_State_Separation', 'The principle of separating church from state in governance.')
ON CONFLICT (id) DO NOTHING;


INSERT INTO options_of_topic(controversial_topics_id, option_id, topic_option) VALUES
  (0,0, 'SAFETY'),
  (0,1, 'FREEDOM'),
  (1,0, 'OPEN BORDER'),
  (1,1, 'CLOSE BORDER'),
  (2,0, 'GREAT IDEA'),
  (2,1, 'HATE THEM'),
  (3,0, 'CAPITALISM'),
  (3,1, 'SOCIALISM'),
  (4,0, 'FREE HEALTHCARE'),
  (4,1, 'MORE WE PAY, BETTER IT IS'),
  (5,0, 'YES, WE LOVE HOMO'),
  (5,1, 'NO, WE LOVE HOMO'),
  (6,0, 'MAN IS A MAN'),
  (6,1, 'GENDER IS FLUID'),
  (7,0, 'RELIGION IS GREAT THING'),
  (7,1, 'OPIUM FOR THE PEOPLE'),
  (8,0, 'FREESPEACH'),
  (8,1, 'THERE ARE THINGS WHICH NEED TO BE CENSURED'),
  (9,0, 'I LOVE SOCIAL MEDIA'),
  (9,1, 'FUCK ZUCKERBERG'),
  (10,0,'I AM POLICEMAN'),
  (10,1,'FUCK THE POLICE'),
  (11,0, 'FRIENDS WITH EVERYBODY'),
  (11,1, 'ONLY BUSINESS'),
  (12,0, 'MONEY FOR EVERYBODY'),
  (12,1, 'MONEY ONLY FOR WORKS'),
  (13,0, 'AI WILL KILL US'),
  (13,1, 'AI WILL UPGRADE US'),
  (14,0, 'HUGE COMPANIES ARE GOOD'),
  (14,1, 'SMALL BUSINESS - BETTER QUALITY'),
  (15,0, 'SURVEILLANCE - SAFETY'),
  (15,1, 'SURVEILLANCE - ENSLAVEMENT'),
  (16,0, 'EDUCATION FOR MONEY'),
  (16,1, 'EDUCATION SHOULD BE FREE'),
  (17,0, 'BODY POSITIVE'),
  (17,1, 'GREEK GOD PHYSIQUES IS NOT ENOUGH'),
  (18,0, 'KABOOM IS NOT GOOD'),
  (18,1, 'CLEAN ENERGY IS COOL'),
  (19,0, 'EVERY CULTURE FOR EVERYBODY'),
  (19,1, 'MY COUNTRY - MY CULTURE'),
  (20,0, 'EMPLOYEE PROTECTION'),
  (20,1, 'FREE MARKET'),
  (21,0, 'NATO AND UN ARE SIGNIFICANT'),
  (21,1, 'NATO AND UN DONT EXIST IN OUR TIMES'),
  (22,0, 'WE SHOULD CHANGE PEOPLES DNA'),
  (22,1, 'GOD WILL KILL US FOR THAT, BETTER NOT'),
  (23,0, 'SPACE CONQUEST IS A CHALLENGE WE WANT TO ACHIEVE'),
  (23,1, 'WE SHOULD FOCUS ON EARTH'),
  (24,0, 'WOMEN WILL BE REPLACED'),
  (24,1, 'IT IS NOT ETHICAL'),
  (25,0, 'BETTER DESTROYING DRONES THAN KILLING PEOPLE'),
  (25,1, 'SAD THAT DRONES DIE FOR PEOPLE'),
  (26,0, 'NO AGE LIMIT FOR SEX'),
  (26,1, 'WE SHOULD PROTECT YOUNG AND OLD'),
  (27,0, 'LOBBYING IS NOT FAIR FOR ORDINARY CITIZENS'),
  (27,1, 'FOR ME ITS OKAY'),
  (28,0, 'WHORES'),
  (28,1, 'SEX WORKERS'),
  (29,0, 'DRUGS EXPENSIVE BUT MODERN'),
  (29,1, 'ACCESS TO DRUGS FOR EVERYONE'),
  (30,0, 'HIGHER MINIMUM WAGE = HIGHER UNEMPLOYMENT'),
  (30,1, 'HIGHER MINIMUM WAGE = BETTER LIFE'),
  (31,0, 'MONARCHY IS OUTDATED'),
  (31,1, 'MONARCHY ADDS STABILITY'),
  (32,0, 'FREE TRADE IS DEVELOPMENT'),
  (32,1, 'PROTECTIONISM PROTECTS JOBS'),
  (33,0, 'DOPING IS CHEATING'),
  (33,1, 'DOPING SHOULD BE LEGAL'),
  (34,0, 'MEDIA UNBIASED'),
  (34,1, 'MEDIA BIASED'),
  (35,0, 'CRYPTOCURRENCIES ARE THE FUTURE'),
  (35,1, 'CRYPTOCURRENCIES ARE A RISK'),
  (36,0, 'POPULATION CONTROL CAN SAVE OUR CHILDREN'),
  (36,1, 'POPULATION CONTROL IS A RIGHTS VIOLATION'),
  (37,0, 'AMERICAN SCHOOL IN OUR SCHOOLS'),
  (37,1, 'LIFE WILL BE SAFER'),
  (38,0, 'TECHNOLOGY HELPS CHILDREN'),
  (38,1, 'TECHNOLOGY KILLS CHILDREN'),
  (39,0, 'CHURCH AND STATE TOGETHER'),
  (39,1, 'STRICT SEPARATION OF CHURCH AND STATE');

